restaurantreview/urls.py
from django.urls import path

from restaurantreview.views import (
    ReviewerList, RestaurantList, DineList, ItemList, LocationList, RatingList, RecipeList, RestaurantDetail,
    DineDetail, ItemDetail, LocationDetail, RatingDetail, ReviewerDetail, RecipeDetail, DineCreate, ItemCreate,
    RatingCreate, ReviewerCreate, RestaurantCreate, LocationCreate, RecipeCreate, ReviewerDelete, RestaurantDelete,
    LocationDelete, RecipeDelete, DineDelete, ItemDelete, RatingDelete, DineUpdate, ReviewerUpdate, RestaurantUpdate,
    ItemUpdate, LocationUpdate, RecipeUpdate, RatingUpdate,
)

urlpatterns = [
    path('reviewer/',
         ReviewerList.as_view(),
         name='restaurantreview_reviewer_list_urlpattern'),
    path('reviewer/<int:pk>/',
         ReviewerDetail.as_view(),
         name='restaurantreview_reviewer_detail_urlpattern'),
    path('reviewer/create/',
         ReviewerCreate.as_view(),
         name='restaurantreview_reviewer_create_urlpattern'),
    path('reviewer/<int:pk>/delete/',
         ReviewerDelete.as_view(),
         name='restaurantreview_reviewer_delete_urlpattern'),
    path('reviewer/<int:pk>/update/',
         ReviewerUpdate.as_view(),
         name='restaurantreview_reviewer_update_urlpattern'),
    path('restaurant/',
         RestaurantList.as_view(),
         name='restaurantreview_restaurant_list_urlpattern'),
    path('restaurant/<int:pk>/',
         RestaurantDetail.as_view(),
         name='restaurantreview_restaurant_detail_urlpattern'),
    path('restaurant/create/',
         RestaurantCreate.as_view(),
         name='restaurantreview_restaurant_create_urlpattern'),
    path('restaurant/<int:pk>/delete/',
         RestaurantDelete.as_view(),
         name='restaurantreview_restaurant_delete_urlpattern'),
    path('restaurant/<int:pk>/update/',
         RestaurantUpdate.as_view(),
         name='restaurantreview_restaurant_update_urlpattern'),
    path('dine/',
         DineList.as_view(),
         name='restaurantreview_dine_list_urlpattern'),
    path('dine/<int:pk>/',
         DineDetail.as_view(),
         name='restaurantreview_dine_detail_urlpattern'),
    path('dine/create/',
         DineCreate.as_view(),
         name='restaurantreview_dine_create_urlpattern'),
    path('dine/<int:pk>/delete/',
         DineDelete.as_view(),
         name='restaurantreview_dine_delete_urlpattern'),
    path('dine/<int:pk>/update/',
         DineUpdate.as_view(),
         name='restaurantreview_dine_update_urlpattern'),
    path('item/',
         ItemList.as_view(),
         name='restaurantreview_item_list_urlpattern'),
    path('item/<int:pk>/',
         ItemDetail.as_view(),
         name='restaurantreview_item_detail_urlpattern'),
    path('item/create/',
         ItemCreate.as_view(),
         name='restaurantreview_item_create_urlpattern'),
    path('item/<int:pk>/delete/',
         ItemDelete.as_view(),
         name='restaurantreview_item_delete_urlpattern'),
    path('item/<int:pk>/update/',
         ItemUpdate.as_view(),
         name='restaurantreview_item_update_urlpattern'),
    path('location/',
         LocationList.as_view(),
         name='restaurantreview_location_list_urlpattern'),
    path('location/<int:pk>/',
         LocationDetail.as_view(),
         name='restaurantreview_location_detail_urlpattern'),
    path('location/create/',
         LocationCreate.as_view(),
         name='restaurantreview_location_create_urlpattern'),
    path('location/<int:pk>/delete/',
         LocationDelete.as_view(),
         name='restaurantreview_location_delete_urlpattern'),
    path('location/<int:pk>/update/',
         LocationUpdate.as_view(),
         name='restaurantreview_location_update_urlpattern'),
    path('recipe/',
         RecipeList.as_view(),
         name='restaurantreview_recipe_list_urlpattern'),
    path('recipe/<int:pk>/',
         RecipeDetail.as_view(),
         name='restaurantreview_recipe_detail_urlpattern'),
    path('recipe/create/',
         RecipeCreate.as_view(),
         name='restaurantreview_recipe_create_urlpattern'),
    path('recipe/<int:pk>/delete/',
         RecipeDelete.as_view(),
         name='restaurantreview_recipe_delete_urlpattern'),
    path('recipe/<int:pk>/update/',
         RecipeUpdate.as_view(),
         name='restaurantreview_recipe_update_urlpattern'),
    path('rating/',
         RatingList.as_view(),
         name='restaurantreview_rating_list_urlpattern'),
    path('rating/<int:pk>/',
         RatingDetail.as_view(),
         name='restaurantreview_rating_detail_urlpattern'),
    path('rating/create/',
         RatingCreate.as_view(),
         name='restaurantreview_rating_create_urlpattern'),
    path('rating/<int:pk>/delete/',
         RatingDelete.as_view(),
         name='restaurantreview_rating_delete_urlpattern'),
    path('rating/<int:pk>/update/',
         RatingUpdate.as_view(),
         name='restaurantreview_rating_update_urlpattern'),

]

schulz_paige_final_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('',
         RedirectView.as_view(
             pattern_name='about_urlpattern',
             permanent=False
         )),
    path('login/',
         LoginView.as_view(template_name='restaurantreview/login.html'),
         name='login_urlpattern'
         ),
    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'
         ),
    path('about/',
         TemplateView.as_view(template_name='restaurantreview/about.html'),
         name='about_urlpattern'
         ),
    path('admin/', admin.site.urls),
    path('', include('restaurantreview.urls'))

]

restaurantreview/models.py
from datetime import datetime

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse


class Reviewer(models.Model):
    reviewer_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField(max_length=45, unique=True)
    middle_name = models.CharField(max_length=45, blank=True, default='')

    def __str__(self):
        result = ''
        if self.middle_name == '':
            result = '%s %s' % (self.first_name, self.last_name)
        else:
            result = '%s %s %s' % (self.first_name, self.middle_name, self.last_name)
        return result

    def get_absolute_url(self):
        return reverse('restaurantreview_reviewer_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('restaurantreview_reviewer_delete_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('restaurantreview_reviewer_update_urlpattern',
                       kwargs={'pk': self.pk})

    class Meta:
        ordering = ['last_name', 'first_name', 'middle_name']
        constraints = [
            UniqueConstraint(fields=['last_name', 'first_name', 'middle_name'], name='unique_reviewer')
        ]


class Restaurant(models.Model):
    restaurant_id = models.AutoField(primary_key=True)
    restaurant_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return '%s' % self.restaurant_name

    def get_absolute_url(self):
        return reverse('restaurantreview_restaurant_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('restaurantreview_restaurant_delete_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('restaurantreview_restaurant_update_urlpattern',
                       kwargs={'pk': self.pk})


class Recipe(models.Model):
    recipe_id = models.AutoField(primary_key=True)
    ingredients = models.CharField(max_length=155, default='')

    def __str__(self):
        return '%s' % self.ingredients

    def get_absolute_url(self):
        return reverse('restaurantreview_recipe_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('restaurantreview_recipe_delete_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('restaurantreview_recipe_update_urlpattern',
                       kwargs={'pk': self.pk})


class Location(models.Model):
    location_id = models.AutoField(primary_key=True)
    street_number = models.IntegerField(unique=True)
    street_name = models.CharField(max_length=45)
    city = models.CharField(max_length=45)
    zipcode = models.IntegerField()
    state = models.CharField(max_length=25)
    restaurant = models.ForeignKey(Restaurant, related_name="locations", on_delete=models.PROTECT)

    def __str__(self):
        return '%s %s %s, %s %s' % (self.street_number, self.street_name, self.city, self.state, self.zipcode)

    def get_absolute_url(self):
        return reverse('restaurantreview_location_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('restaurantreview_location_delete_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('restaurantreview_location_update_urlpattern',
                       kwargs={'pk': self.pk})

    class Meta:
        ordering = ['street_number', 'street_name']
        constraints = [
            UniqueConstraint(fields=['street_number', 'street_name', 'city', 'state'], name='unique_location')
        ]


class Item(models.Model):
    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=45)
    item_cost = models.DecimalField(decimal_places=2, max_digits=6)
    recipe = models.ForeignKey(Recipe, related_name="items", on_delete=models.PROTECT, null=True)

    def __str__(self):
        return '%s - %s' % (self.item_name, self.item_cost)

    def get_absolute_url(self):
        return reverse('restaurantreview_item_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('restaurantreview_item_delete_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('restaurantreview_item_update_urlpattern',
                       kwargs={'pk': self.pk})

    class Meta:
        ordering = ['item_name', 'item_cost']


class Rating(models.Model):
    rating_id = models.AutoField(primary_key=True)
    stars_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    comment = models.CharField(max_length=250, default='')
    reviewer = models.ForeignKey(Reviewer, related_name="ratings", on_delete=models.PROTECT)
    item = models.ForeignKey(Item, related_name="ratings", on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s' % (self.stars_rating, self.comment)

    def get_absolute_url(self):
        return reverse('restaurantreview_rating_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('restaurantreview_rating_delete_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('restaurantreview_rating_update_urlpattern',
                       kwargs={'pk': self.pk})

    class Meta:
        ordering = ['stars_rating']


class Dine(models.Model):
    dine_at_id = models.AutoField(primary_key=True)
    date = models.DateTimeField(blank=True, null=True)
    location = models.ForeignKey(Location, related_name="dines", on_delete=models.PROTECT)
    reviewer = models.ForeignKey(Reviewer, related_name="dines", on_delete=models.PROTECT)

    def __str__(self):
        return '%s' % self.date

    def get_absolute_url(self):
        return reverse('restaurantreview_dine_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('restaurantreview_dine_delete_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('restaurantreview_dine_update_urlpattern',
                       kwargs={'pk': self.pk})

    class Meta:
        ordering = ['date', 'location', 'reviewer']
        constraints = [
            UniqueConstraint(fields=['date', 'location'], name='unique_rating')
        ]

restaurantreview/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.forms import DateField, NumberInput

from restaurantreview.models import Dine, Recipe, Rating, Restaurant, Reviewer, Item, Location


class DineForm(forms.ModelForm):
    class Meta:
        model = Dine
        fields = '__all__'
        widgets = {
            'date': forms.DateTimeInput(attrs={'class': 'datetime-input'})
        }

        def clean_location(self):
            return self.cleaned_data['location'].strip()


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

        def clean_item_name(self):
            return self.cleaned_data['item_name'].strip()

        def clean_item_cost(self):
            return self.cleaned_data['item_cost'].strip()


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'

        def clean_street_number(self):
            return self.cleaned_data['street_number'].strip()

        def clean_street_name(self):
            return self.cleaned_data['street_name'].strip()

        def clean_city(self):
            return self.cleaned_data['city'].strip()

        def clean_zipcode(self):
            return self.cleaned_data['zipcode'].strip()

        def clean_state(self):
            return self.cleaned_data['state'].strip()


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = '__all__'

        def clean_stars_rating(self):
            return self.cleaned_data['stars_rating'].strip()

        def clean_comment(self):
            return self.cleaned_data['comment'].strip()


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'

        def clean_ingredients(self):
            return self.cleaned_data['ingredients'].strip()


class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = '__all__'

        def clean_restaurant_name(self):
            return self.cleaned_data['restaurant_name'].strip()


class ReviewerForm(forms.ModelForm):
    class Meta:
        model = Reviewer
        fields = '__all__'

        def clean_first_name(self):
            return self.cleaned_data['first_name'].strip()

        def clean_last_name(self):
            return self.cleaned_data['last_name'].strip()

        def clean_middle_name(self):
            if len(self.cleaned_data['middle_name']) == 0:
                result = self.cleaned_data['middle_name']
            else:
                result = self.cleaned_data['middle_name'].strip()
            return result

restaurantreview/templates/restaurantreview/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            title is provided by inheriting templates
        {% endblock %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if IE]>
    <script
            src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script><![endif]-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'restaurantreview/normalize.css' %}?version=4">
    <link rel="stylesheet" type="text/css"
          href="{% static 'restaurantreview/skeleton.css' %}?version=4">
    <link rel="stylesheet" type="text/css"
          href="{% static 'restaurantreview/style.css' %}?version=4">
    {% block head %}{% endblock %}
</head>

<body>

<div><!-- start of container -->
    <div class="status row">
        <div class="offset-by-eight four columns">
            <ul class="inline">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout_urlpattern' %}">
                        Log Out, {{ user.get_username }}</a></li>
                {% else %}
                    <li><a href="{% url 'login_urlpattern' %}">
                        Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <header>
        <h1>Restaurant Review</h1>
    </header>
    <nav>
        <ul>
            {% if perms.restaurantreview.view_dine %}
                <li>
                    <a href="{% url 'restaurantreview_dine_list_urlpattern' %}">
                        Dining</a></li>
            {% endif %}
            {% if perms.restaurantreview.view_reviewer %}
                <li>
                    <a href="{% url 'restaurantreview_reviewer_list_urlpattern' %}">
                        Reviewers</a></li>
            {% endif %}
            {% if perms.restaurantreview.view_restaurant %}
                <li>
                    <a href="{% url 'restaurantreview_restaurant_list_urlpattern' %}">
                        Restaurants</a></li>
            {% endif %}
            {% if perms.restaurantreview.view_location %}
                <li>
                    <a href="{% url 'restaurantreview_location_list_urlpattern' %}">
                        Locations</a></li>
            {% endif %}
            {% if perms.restaurantreview.view_item %}
                <li>
                    <a href="{% url 'restaurantreview_item_list_urlpattern' %}">
                        Items</a></li>
            {% endif %}
            {% if perms.restaurantreview.view_rating %}
                <li>
                    <a href="{% url 'restaurantreview_rating_list_urlpattern' %}">
                        Rating</a></li>
            {% endif %}
            {% if perms.restaurantreview.view_recipe %}
                <li>
                    <a href="{% url 'restaurantreview_recipe_list_urlpattern' %}">
                        Recipes</a></li>
            {% endif %}

            <li>
                <a href="{% url 'about_urlpattern' %}">
                    About</a></li>
        </ul>
    </nav>
    <main>
        {% block content %}

        {% endblock %}
    </main>
</div><!-- end of container -->

</body>
</html>

restaurantreview/templates/restaurantreview/dine_list.html
{% extends 'restaurantreview/base.html' %}
{% block title %}
    Dining List
{% endblock %}

{% block content %}
    <h1>Dining</h1>
    {% block create_button %}
        {% if perms.restaurantreview.add_dine %}
            <a
                    href="{% url 'restaurantreview_dine_create_urlpattern' %}"
                    class="button button-primary">
                Create New Dining</a>
        {% endif %}
    {% endblock %}
    <ol>
        {% for dine in dine_list %}
            <li>
                <a href="{{ dine.get_absolute_url }}">
                    {{ dine }}</a>
            </li>
        {% empty %}
            <li><em> There are no previous dinings.</em></li>
        {% endfor %}
    </ol>
{% endblock %}

restaurantreview/templates/restaurantreview/item_detail.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Item - {{ item }}
{% endblock %}

{% block content %}
    <h2>{{ item }}</h2>
    <ul class="ezu-button-list">
        {% if perms.restaurantreview.change_item %}
            <li>
                <a href="{{ item.get_update_url }}"
                   class="button button-primary">
                    Edit Item</a></li>
        {% endif %}
        {% if perms.restaurantreview.delete_item %}
            <li>
                <a href="{{ item.get_delete_url }}"
                   class="button button-primary">
                    Delete Item</a></li>
        {% endif %}

    </ul>

    <section>
        <table>
            <tr>
                <th>Name:</th>
                <td>{{ item.item_name }}</td>
            </tr>
        </table>
        <table>
            <tr>
                <th>Cost:</th>
                <td>{{ item.item_cost }}</td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Rating</h3>
        <ul>
            {% for rating in rating_list %}
                <li>
                    <a href="{{ rating.get_absolute_url }}">{{ rating }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no ratings for this item.</em></li>
            {% endfor %}
        </ul>
        <h3>Recipe</h3>
        <a href="{{ recipe.get_absolute_url }}">{{ recipe }}</a>
    </section>
{% endblock %}

restaurantreview/templates/restaurantreview/item_list.html
{% extends 'restaurantreview/base.html' %}
{% block title %}
    Item List
{% endblock %}

{% block content %}
    <h1>Items</h1>
    {% block create_button %}
        {% if perms.restaurantreview.add_item %}
            <a
                    href="{% url 'restaurantreview_item_create_urlpattern' %}"
                    class="button button-primary">
                Create New Item</a>
        {% endif %}
    {% endblock %}

    <ol>
        {% for item in item_list %}
            <li>
                <a href="{{ item.get_absolute_url }}">
                    {{ item }}</a>
            </li>
        {% empty %}
            <li><em> There are no items.</em></li>
        {% endfor %}
    </ol>
{% endblock %}

restaurantreview/templates/restaurantreview/item_refuse_delete.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Error Deleting Item
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Item</h2>
        <p>
            You may not delete item {{ item }}. This item currently has the following ratings associated
            with it :
        </p>

        <ul>
            {% for rating in ratings %}
                <li><a href="{{ rating.get_absolute_url }}">{{ rating }}</a></li>
            {% endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'restaurantreview_rating_list_urlpattern' %}">Rating List</a>.
        </p>
    </div>
{% endblock %}

restaurantreview/templates/restaurantreview/rating_confirm_delete.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Delete Rating
{% endblock %}

{% block content %}
    <form
            action="{{ rating.get_delete_url }}"
            method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            rating {{ rating }}?
        </p>
        <a href="{{ rating.get_absolute_url }}"
           class="button button-primary">
            Cancel</a>
        <button type="submit" class="button button-primary">Delete Rating</button>
    </form>
{% endblock %}

restaurantreview/templates/restaurantreview/rating_form.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Create Rating
{% endblock %}

{% block content %}
    <form
            action="{% url 'restaurantreview_rating_create_urlpattern' %}"
            method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Create Rating</button>
    </form>
{% endblock %}

restaurantreview/templates/restaurantreview/recipe_confirm_delete.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Delete Recipe
{% endblock %}

{% block content %}
    <form
            action="{{ recipe.get_delete_url }}"
            method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            recipe {{ recipe }}?
        </p>
        <a href="{{ recipe.get_absolute_url }}"
           class="button button-primary">
            Cancel</a>
        <button type="submit" class="button button-primary">Delete Recipe</button>
    </form>
{% endblock %}

restaurantreview/templates/restaurantreview/recipe_detail.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Recipe - {{ recipe }}
{% endblock %}

{% block content %}
    <h2>{{ recipe }}</h2>
    <ul class="ezu-button-list">
        {% if perms.restaurantreview.change_recipe %}
            <li>
                <a href="{{ recipe.get_update_url }}"
                   class="button button-primary">
                    Edit Recipe</a></li>
        {% endif %}
        {% if perms.restaurantreview.delete_recipe %}
            <li>
                <a href="{{ recipe.get_delete_url }}"
                   class="button button-primary">
                    Delete Recipe</a></li>
        {% endif %}
    </ul>

    <section>
        <table>
            <tr>
                <th>Ingredients:</th>
                <td>{{ recipe.ingredients }}</td>
            </tr>
        </table>
    </section>
    <section>
        <h1>Items</h1>
        <ol>
            {% for item in item_list %}
                <li>
                    <a href="{{ item.get_absolute_url }}">
                        {{ item }}</a>
                </li>
            {% empty %}
                <li><em> This recipe has no items.</em></li>
            {% endfor %}
        </ol>
    </section>
{% endblock %}

restaurantreview/templates/restaurantreview/recipe_form_update.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Update Recipe
{% endblock %}

{% block content %}
    <form
            action="{{ recipe.get_update_url }}"
            method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Recipe</button>
    </form>
{% endblock %}

restaurantreview/templates/restaurantreview/recipe_list.html
{% extends 'restaurantreview/base.html' %}
{% block title %}
    Recipe List
{% endblock %}

{% block content %}
    <h1>Recipes</h1>
    {% block create_button %}
        {% if perms.restaurantreview.add_recipe %}
            <a
                    href="{% url 'restaurantreview_recipe_create_urlpattern' %}"
                    class="button button-primary">
                Create New Recipe</a>
        {% endif %}
    {% endblock %}
    <ol>
        {% for recipe in recipe_list %}

            <li>
                <a href="{{ recipe.get_absolute_url }}">
                    {{ recipe }}</a>
            </li>
        {% empty %}
            <li><em> There are no recipes.</em></li>
        {% endfor %}
    </ol>
{% endblock %}

restaurantreview/templates/restaurantreview/restaurant_confirm_delete.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Delete Restaurant
{% endblock %}

{% block content %}
    <form
            action="{{ restaurant.get_delete_url }}"
            method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            restaurant {{ restaurant }}?
        </p>
        <a href="{{ restaurant.get_absolute_url }}"
           class="button button-primary">
            Cancel</a>
        <button type="submit" class="button button-primary">Delete Restaurant</button>
    </form>
{% endblock %}

restaurantreview/templates/restaurantreview/restaurant_detail.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Restaurant - {{ restaurant }}
{% endblock %}

{% block content %}
    <h2>{{ restaurant }}</h2>
    <ul class="ezu-button-list">
        {% if perms.restaurantreview.change_restaurant %}
            <li>
                <a href="{{ restaurant.get_update_url }}"
                   class="button button-primary">
                    Edit Restaurant</a></li>
        {% endif %}
        {% if perms.restaurantreview.delete_restaurant %}
            <li>
                <a href="{{ restaurant.get_delete_url }}"
                   class="button button-primary">
                    Delete Restaurant</a></li>
        {% endif %}
    </ul>

    <section>
        <table>
            <tr>
                <th>Name:</th>
                <td>{{ restaurant.restaurant_name }}</td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Locations</h3>
        <ul>
            {% for location in location_list %}
                <li>
                    <a href="{{ location.get_absolute_url }}">{{ location }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no locations for this restaurant.</em></li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

restaurantreview/templates/restaurantreview/reviewer_refuse_delete.html
{% extends 'restaurantreview/base.html' %}

{% block title %}
    Error Deleting Reviewer
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Reviewer</h2>
        <p>
            You may not delete reviewer {{ reviewer }}. This reviewer currently has the following ratings:
        </p>

        <ul>
            {% for rating in ratings %}
                <li><a href="{{ rating.get_absolute_url }}">{{ rating }}</a></li>
            {% endfor %}
        </ul>
        <ul>
            {% for dine in dines %}
                <li><a href="{{ dine.get_absolute_url }}">{{ dine }}</a></li>
            {% endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'restaurantreview_reviewer_list_urlpattern' %}">Reviewer List</a>.
        </p>
    </div>
{% endblock %}